apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy-springboot-app-deployment
  name: dummy-springboot-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-springboot-app-deployment
  strategy: { }
  template:
    metadata:
      labels:
        app: dummy-springboot-app-deployment
    spec:
      containers:
        - image: jahidshohel/dummy-springboot:1.0
          name: dummy-springboot
          resources: { }
